### ISSUE TITLE
Auto-Revert: Don't start the timer until there is a change

### ISSUE THREAD

**Issue by yjaaidi** [dkandalov/limited-wip#19]
Hi @dkandalov!
First of all thank you for this great tool. Good job!

I really appreciate the auto-revert but the problem is that the timer starts immediately after the commit / revert. I would love it to only start when I start coding again. Otherwise, I could commit, go read some documentation, come back to write something an I would only have 10 seconds or something :). You can check that out here: https://www.youtube.com/watch?v=4a98KvVJFRw

What would you think about waiting for `currentChangeListSizeInLines` to be non-empty in auto-revert before starting the timer.

Instead of reseting the counter if there's a revert, it would be reset every time there are no more changes ( commit / revert / undo...).

Thank you!

**Comment by dkandalov** [comment]
Hi @yjaaidi,

Thanks a lot and sorry for the slow reply.
Also thank you for sharing youtube videos :)

Waiting for `currentChangeListSizeInLines` to be non-empty before restarting timer sounds like a good idea to me and it shouldn't be too hard to implement I guess. Maybe the timer should also start automatically after first change instead of clicking on auto-revert in the toolbar, this will simplify UI 🤔

Replacing logic from watching particular actions (like commit and revert) to just monitor amount of changes might be a good idea. I don't feel too confident about this change but I should probably try it and see how it works in practice.

**Comment by yjaaidi** [comment]
Hi @dkandalov,

There is no hurry 😊.

> Waiting for currentChangeListSizeInLines to be non-empty before restarting timer sounds like a good idea to me and it shouldn't be too hard to implement I guess. Maybe the timer should also start automatically after first change instead of clicking on auto-revert in the toolbar, this will simplify UI 🤔

Exactly! That would be perfect!

>Replacing logic from watching particular actions (like commit and revert) to just monitor amount of changes might be a good idea. I don't feel too confident about this change but I should probably try it and see how it works in practice.

I guess it should work. We could monitor the amount of changes and also trigger that when a commit or revert happens to make sure there's no delay or anything.

Let's try and see. By the way, if you need any help, let me know. I am not used to Kotlin & IntelliJ plugin development but I am still interested.

**Comment by dkandalov** [comment]
Done in plugin version 0.3.3 (it will be available in couple days after jetbrains approves it).

**Comment by yjaaidi** [comment]
Great job Dmitry!!! I love it!!!!
