### ISSUE TITLE
Is there a way to disable by project ?

### ISSUE THREAD

**Issue by jpbelang** [dkandalov/limited-wip#22]
I have a bunch of projects and would like to activate by project.

Is this a feature that would be feasible ?

(That said, this code is really cool :-) )

**Comment by dkandalov** [comment]
Yes, I thought about something like that a while ago (see issue #11).
What do you mean by "activate by project"? Have all settings configured per project?

**Comment by jpbelang** [comment]
Pretty much (or maybe override by project).  I have some projects no written by me that don't work well with TCR (where the tests can fail in surprising ways).  Even the size of the commits can get out of hand because of changing data.  In these projects, I'd like to either stop the plugin entirely or partly.

In my projects, I'm rather enjoying using it and it's really helping the flow of my work in general.

**Comment by dkandalov** [comment]
I had pretty much the same experience. The main reason I didn't implement it was that updating the same setting for each project can be very tedious. Maybe this is not really a problem and I should just try per-project settings.

**Comment by dkandalov** [comment]
I made all plugin settings to be scoped by current project.
Unfortunately, your current application-level settings will be lost on plugin update (because it's not very clear how to do migration, should the current settings become default for all new projects? probably not).

This should work starting from [v0.3.6](https://github.com/dkandalov/limited-wip/releases/tag/v0.3.6) once it's approved by jetbrains.
