### ISSUE TITLE
Reset Time if the code is reverted

### ISSUE THREAD

**Issue by ollin** [dkandalov/limited-wip#9]
Scenario:

Using the clock as the constraint. 

_editing one File ->  Editor -> mouse right click -> Git -> revert_

resets the file in the original state. The clock does not change.

Improvement:

Reset the clock as well.

**Comment by dkandalov** [comment]
Implemented so that timer is reset after revert, if there are no changes left in the current changelist.

There are few caveats though:
 - The notion of reverting is a bit vague, i.e. there are other actions which "revert" changes like shelving changes, undoing changes in editor until there are no changes left, clicking on the gutter in editor and reverting changes one-by-one or reverting changes via git on command line. This feature only resets timer on `Revert` action in IDE.
 - There are (at least) two ways to invoke `Revert` action `File -> Editor -> mouse right click -> Git -> revert` and `VCS Operations Popup -> Revert`. Both ways seem to work ok in IJ 2018 but the second way via popup is not detected as revert in IJ 2017.3 (I suspect it was some IJ implementation issue which is fixed now).

**Comment by ollin** [comment]
thx!

**Comment by ollin** [comment]
thx!
